name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough details to reproduce.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong?
      placeholder: Short bug summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps
      placeholder: |
        1. Open ...
        2. Tap ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g. v1.6.1
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device/Android version
      placeholder: e.g. Pixel 7, Android 14
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste stacktrace or add screenshots
      render: shell
    validations:
      required: false
