name: Feature request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the user problem first, then the proposed solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem should be solved?
      placeholder: As a student, I want ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be built?
      placeholder: Add a new option in ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any other options?
    validations:
      required: false
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits and why?
      placeholder: Improves onboarding for new users
    validations:
      required: false
