package com.andrin.examcountdown.ui.theme

import androidx.compose.ui.graphics.Color

// Twilight palette: blue carries orientation and time; jade marks progress and healthy sync states.
val BluePrimaryLight = Color(0xFF0E4C82)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFD9ECFA)
val BlueOnPrimaryContainerLight = Color(0xFF0B2D49)
val BlueSecondaryLight = Color(0xFF087E68)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFC9F1E4)
val BlueOnSecondaryContainerLight = Color(0xFF073B31)
val BlueAccentLight = Color(0xFF2474B5)
val BlueOnAccentLight = Color(0xFFFFFFFF)
val BlueAccentContainerLight = Color(0xFFD3E8FB)
val BlueOnAccentContainerLight = Color(0xFF0E3554)
val BackgroundLight = Color(0xFFF3F6FA)
val OnBackgroundLight = Color(0xFF132026)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF132026)
val SurfaceVariantLight = Color(0xFFE3EDF2)
val OnSurfaceVariantLight = Color(0xFF50606B)
val OutlineLight = Color(0xFF5B6E77)
val OutlineVariantLight = Color(0xFFC8D3D8)
val InverseSurfaceLight = Color(0xFF132026)
val InverseOnSurfaceLight = Color(0xFFEDF7F8)
val InversePrimaryLight = Color(0xFF9DD5FF)

val BluePrimaryDark = Color(0xFF57B8FF)
val BlueOnPrimaryDark = Color(0xFF06243A)
val BluePrimaryContainerDark = Color(0xFF0E4C82)
val BlueOnPrimaryContainerDark = Color(0xFFDDF2FF)
val BlueSecondaryDark = Color(0xFF69E5B0)
val BlueOnSecondaryDark = Color(0xFF063126)
val BlueSecondaryContainerDark = Color(0xFF0B5C4B)
val BlueOnSecondaryContainerDark = Color(0xFFD1F8E9)
val BlueAccentDark = Color(0xFF8BCBFF)
val BlueOnAccentDark = Color(0xFF06243A)
val BlueAccentContainerDark = Color(0xFF174B70)
val BlueOnAccentContainerDark = Color(0xFFD8EEFF)
val BackgroundDark = Color(0xFF081827)
val OnBackgroundDark = Color(0xFFEDF7F8)
val SurfaceDark = Color(0xFF112B40)
val OnSurfaceDark = Color(0xFFEDF7F8)
val SurfaceVariantDark = Color(0xFF16364D)
val OnSurfaceVariantDark = Color(0xFFB5C9D0)
val OutlineDark = Color(0xFF8EABB8)
val OutlineVariantDark = Color(0xFF365367)
val InverseSurfaceDark = Color(0xFFEDF7F8)
val InverseOnSurfaceDark = Color(0xFF132026)
val InversePrimaryDark = Color(0xFF0E4C82)
