package com.andrin.examcountdown.ui.theme

import androidx.compose.ui.graphics.Color

val BluePrimaryLight = Color(0xFF2849B0)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFE2E8FF)
val BlueOnPrimaryContainerLight = Color(0xFF14245F)
val BlueSecondaryLight = Color(0xFF365EAE)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFE3EBFC)
val BlueOnSecondaryContainerLight = Color(0xFF1D3767)
val BlueAccentLight = Color(0xFF48679E)
val BlueOnAccentLight = Color(0xFFFFFFFF)
val BlueAccentContainerLight = Color(0xFFE8EEFB)
val BlueOnAccentContainerLight = Color(0xFF253B64)
val BackgroundLight = Color(0xFFF6F8FC)
val OnBackgroundLight = Color(0xFF20263A)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF20263A)
val SurfaceVariantLight = Color(0xFFEDF1F8)
val OnSurfaceVariantLight = Color(0xFF555C6D)
val OutlineLight = Color(0xFF777E8D)
val OutlineVariantLight = Color(0xFFD7DFED)
val InverseSurfaceLight = Color(0xFF20263A)
val InverseOnSurfaceLight = Color(0xFFEEF0F8)
val InversePrimaryLight = Color(0xFFB9C8FF)

val BluePrimaryDark = Color(0xFFB9C8FF)
val BlueOnPrimaryDark = Color(0xFF182960)
val BluePrimaryContainerDark = Color(0xFF2D4281)
val BlueOnPrimaryContainerDark = Color(0xFFDFE5FF)
val BlueSecondaryDark = Color(0xFFB4C9F4)
val BlueOnSecondaryDark = Color(0xFF19345E)
val BlueSecondaryContainerDark = Color(0xFF30476D)
val BlueOnSecondaryContainerDark = Color(0xFFDDE8FF)
val BlueAccentDark = Color(0xFFBACCF2)
val BlueOnAccentDark = Color(0xFF243D66)
val BlueAccentContainerDark = Color(0xFF394D70)
val BlueOnAccentContainerDark = Color(0xFFE0E9FF)
val BackgroundDark = Color(0xFF101723)
val OnBackgroundDark = Color(0xFFEEF0F8)
val SurfaceDark = Color(0xFF182131)
val OnSurfaceDark = Color(0xFFEEF0F8)
val SurfaceVariantDark = Color(0xFF293142)
val OnSurfaceVariantDark = Color(0xFFB9C0D0)
val OutlineDark = Color(0xFF939BAC)
val OutlineVariantDark = Color(0xFF414A5C)
val InverseSurfaceDark = Color(0xFFEEF0F8)
val InverseOnSurfaceDark = Color(0xFF20263A)
val InversePrimaryDark = Color(0xFF2849B0)
