package com.andrin.examcountdown.ui.theme

import androidx.compose.ui.graphics.Color

// Neutral white and graphite surfaces; restrained steel blue marks actions.
// Both modes share the same surface hierarchy and clear boundaries.
val AppPrimaryLight = Color(0xFF405A78)
val AppOnPrimaryLight = Color(0xFFFFFFFF)
val AppPrimaryContainerLight = Color(0xFFE8EDF3)
val AppOnPrimaryContainerLight = Color(0xFF243447)
val AppSecondaryLight = Color(0xFF53606D)
val AppOnSecondaryLight = Color(0xFFFFFFFF)
val AppSecondaryContainerLight = Color(0xFFEDF0F3)
val AppOnSecondaryContainerLight = Color(0xFF303B47)
val AppAccentLight = Color(0xFF405A78)
val AppOnAccentLight = Color(0xFFFFFFFF)
val AppAccentContainerLight = Color(0xFFE8EDF3)
val AppOnAccentContainerLight = Color(0xFF243447)
val BackgroundLight = Color(0xFFF3F5F7)
val OnBackgroundLight = Color(0xFF20252B)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF20252B)
val SurfaceVariantLight = Color(0xFFEDF0F3)
val OnSurfaceVariantLight = Color(0xFF535F6B)
val OutlineLight = Color(0xFF6F7B88)
val OutlineVariantLight = Color(0xFFCDD4DC)
val InverseSurfaceLight = Color(0xFF252B32)
val InverseOnSurfaceLight = Color(0xFFF4F6F8)
val InversePrimaryLight = Color(0xFFB6CBE2)

val AppPrimaryDark = Color(0xFFB6CBE2)
val AppOnPrimaryDark = Color(0xFF182E45)
val AppPrimaryContainerDark = Color(0xFF303D4D)
val AppOnPrimaryContainerDark = Color(0xFFE1EAF4)
val AppSecondaryDark = Color(0xFFC3CDD7)
val AppOnSecondaryDark = Color(0xFF25313D)
val AppSecondaryContainerDark = Color(0xFF2E353E)
val AppOnSecondaryContainerDark = Color(0xFFE4EAF0)
val AppAccentDark = Color(0xFFB6CBE2)
val AppOnAccentDark = Color(0xFF182E45)
val AppAccentContainerDark = Color(0xFF303D4D)
val AppOnAccentContainerDark = Color(0xFFE1EAF4)
val BackgroundDark = Color(0xFF171B20)
val OnBackgroundDark = Color(0xFFE9EDF2)
val SurfaceDark = Color(0xFF22272E)
val OnSurfaceDark = Color(0xFFE9EDF2)
val SurfaceVariantDark = Color(0xFF30373F)
val OnSurfaceVariantDark = Color(0xFFC0C9D3)
val OutlineDark = Color(0xFF9AA8B7)
val OutlineVariantDark = Color(0xFF47515D)
val InverseSurfaceDark = Color(0xFFE9EDF2)
val InverseOnSurfaceDark = Color(0xFF252B32)
val InversePrimaryDark = Color(0xFF405A78)
